### PR TITLE
fix cpm_array() when order = 'F'

### PR DESCRIPTION
**Pull request by Wout4**
fixes https://github.com/CPMpy/cpmpy/issues/554

### CODE REVIEW

**Comment by Wout4** [comment]
accidently gave commit the wrong name..

**Comment by Wout4** [comment]
seems that our NDVarArray constructor is actually setting the base property to the args of the array, so it contains the flatlist of elements..

**Comment by Wout4** [comment]
we can compare the base and the array but that seems a bit excessive

**Comment by Wout4** [comment]
```
data = np.array([_BoolVarImpl(name=n) for n in names])
    # insert into custom ndarray
    r = NDVarArray(shape, dtype=object, buffer=data)
```
in our constructor of boolvar and intvar, we make an array out of data so base is not none anymore

**Comment by tias** [comment]
I remember I tried a couple of things to instantiate a ndarray subclass, and only the above one worked with my very limited knowledge (and patience) at the time...

So, if we know of a better way to initialise NDVarArray... one that is more 'view' compatible, that would be very welcome...

**Comment by IgnaceBleukx** [comment]
Wait, but this is about the `cpm_array` helper method, right?
We don't call the cpm_array method when constructing an array of variables, there we simply wrap the freshly created numpy array into an NDVarArray, which seems correct to me.

I'm proposing to _always_ copy the buffer of the input array when using `cpm_array`, so that it mimics the numpy behaviour.
Secondly, I think we should copy the buffer when initialising `NDVarArray` when the given array is a view. I don't think the latter would really matter for our use-case, but a user may call the constructor directly...

**Comment by tias** [comment]
if you look at the commit in this PR, that is what we already did, and now Wout is just also taking the 'order' into account... so all good for this patch?


(btw our 'friend' noted that to make our custom objects more view-compatible, we can do something like:
```
    def __array_finalize__(self, obj):
        """
        This method is called automatically when a view of the array is created.
        It allows you to propagate custom attributes to the view.
        """
        if obj is None:
            return
        # Copy custom attributes from the source object
        self.description = getattr(obj, 'description', None)
```
e.g. we can do that to set 'name' and '_args' and _has_subexpr instead of what we do inside the __repr__ now; Yes, I'm totally abusing this PR, if its relevant I can open a separate issue?

**Comment by IgnaceBleukx** [comment]
Yes for this patch indeed it's fine, let's move the broader discussion to a new issue :)

**Comment by Wout4** [comment]
so we can merge this? think we need it anyway, wether we make copy or not

**Comment by IgnaceBleukx** [comment]
Jup fine to merge indeed - maybe add a small test for it>

**Comment by Wout4** [comment]
I opened a different issue for the copy/view thing
Maybe you should also open one @tias , I'm not sure how to phrase what you want ;)

**Pull request merged**
